include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    use_build_context_synchronously: true
    depend_on_referenced_packages: false

analyzer:
  exclude: [ '**.g.dart', '**.mocks.dart', '**.freezed.dart', '**.config.dart', '**all_imports_test.dart', '**translations*.i18n.dart' ]
  errors:
    always_require_non_null_named_parameters: warning
    annotate_overrides: warning
    avoid_empty_else: warning
    avoid_function_literals_in_foreach_calls: warning
    avoid_init_to_null: warning
    avoid_null_checks_in_equality_operators: warning
    avoid_print: warning
    avoid_relative_lib_imports: warning
    avoid_renaming_method_parameters: warning
    avoid_return_types_on_setters: warning
    avoid_returning_null_for_void: warning
    avoid_shadowing_type_parameters: warning
    avoid_single_cascade_in_expression_statements: warning
    avoid_types_as_parameter_names: warning
    avoid_unnecessary_containers: warning
    avoid_web_libraries_in_flutter: warning
    await_only_futures: warning
    camel_case_extensions: warning
    camel_case_types: warning
    constant_identifier_names: warning
    control_flow_in_finally: warning
    curly_braces_in_flow_control_structures: warning
    depend_on_referenced_packages: warning
    empty_catches: warning
    empty_constructor_bodies: warning
    empty_statements: warning
    exhaustive_cases: warning
    file_names: warning
    hash_and_equals: warning
    implementation_imports: warning
    invalid_use_of_visible_for_overriding_member: warning
    iterable_contains_unrelated_type: warning
    library_names: warning
    library_prefixes: warning
    library_private_types_in_public_api: warning
    list_remove_unrelated_type: warning
    no_duplicate_case_values: warning
    no_leading_underscores_for_library_prefixes: warning
    no_leading_underscores_for_local_identifiers: warning
    no_logic_in_create_state: warning
    non_constant_identifier_names: warning
    null_check_on_nullable_type_parameter: warning
    null_closures: warning
    overridden_fields: warning
    package_names: warning
    package_prefixed_library_names: warning
    parameter_assignments: warning
    prefer_adjacent_string_concatenation: warning
    prefer_collection_literals: warning
    prefer_conditional_assignment: warning
    prefer_const_constructors: warning
    prefer_const_constructors_in_immutables: warning
    prefer_const_declarations: warning
    prefer_const_literals_to_create_immutables: warning
    prefer_contains: warning
    prefer_equal_for_default_values: warning
    prefer_final_fields: warning
    prefer_for_elements_to_map_fromIterable: warning
    prefer_function_declarations_over_variables: warning
    prefer_generic_function_type_aliases: warning
    prefer_if_null_operators: warning
    prefer_initializing_formals: warning
    prefer_inlined_adds: warning
    prefer_interpolation_to_compose_strings: warning
    prefer_is_empty: warning
    prefer_is_not_empty: warning
    prefer_is_not_operator: warning
    prefer_iterable_whereType: warning
    prefer_null_aware_operators: warning
    prefer_spread_collections: warning
    prefer_typing_uninitialized_variables: warning
    prefer_void_to_null: warning
    provide_deprecation_message: warning
    recursive_getters: warning
    sized_box_for_whitespace: warning
    slash_for_doc_comments: warning
    sort_child_properties_last: warning
    type_init_formals: warning
    unnecessary_brace_in_string_interps: warning
    unnecessary_const: warning
    unnecessary_constructor_name: warning
    unnecessary_getters_setters: warning
    unnecessary_late: warning
    unnecessary_new: warning
    unnecessary_non_null_assertion: warning
    unnecessary_null_aware_assignments: warning
    unnecessary_null_in_if_null_operators: warning
    unnecessary_nullable_for_final_variable_declarations: warning
    unnecessary_overrides: warning
    unnecessary_string_escapes: warning
    unnecessary_string_interpolations: warning
    unnecessary_this: warning
    unrelated_type_equality_checks: warning
    unused_element: warning
    use_build_context_synchronously: warning
    use_full_hex_values_for_flutter_colors: warning
    use_function_type_syntax_for_parameters: warning
    use_key_in_widget_constructors: warning
    use_rethrow_when_possible: warning
    valid_regexps: warning
    void_checks: warning