include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    use_build_context_synchronously: true
    depend_on_referenced_packages: false

analyzer:
  exclude: [ '**.g.dart', '**.mocks.dart', '**.freezed.dart', '**.config.dart', '**all_imports_test.dart', '**translations*.i18n.dart' ]
  errors:
    invalid_use_of_visible_for_overriding_member: error
    unused_element: error
    unnecessary_non_null_assertion: error
    sort_child_properties_last: error
    parameter_assignments: error
    avoid_print: error
    avoid_unnecessary_containers: error
    avoid_web_libraries_in_flutter: error
    no_logic_in_create_state: error
    prefer_const_constructors: error
    prefer_const_constructors_in_immutables: error
    prefer_const_declarations: error
    prefer_const_literals_to_create_immutables: error
    sized_box_for_whitespace: error
    use_build_context_synchronously: error
    use_full_hex_values_for_flutter_colors: error
    use_key_in_widget_constructors: error
    avoid_empty_else: error
    avoid_relative_lib_imports: error
    avoid_shadowing_type_parameters: error
    avoid_types_as_parameter_names: error
    await_only_futures: error
    camel_case_extensions: error
    camel_case_types: error
    curly_braces_in_flow_control_structures: error
    depend_on_referenced_packages: error
    empty_catches: error
    file_names: error
    hash_and_equals: error
    iterable_contains_unrelated_type: error
    list_remove_unrelated_type: error
    no_duplicate_case_values: error
    non_constant_identifier_names: error
    null_check_on_nullable_type_parameter: error
    package_prefixed_library_names: error
    prefer_generic_function_type_aliases: error
    prefer_is_empty: error
    prefer_is_not_empty: error
    prefer_iterable_whereType: error
    prefer_typing_uninitialized_variables: error
    provide_deprecation_message: error
    unnecessary_overrides: error
    unrelated_type_equality_checks: error
    valid_regexps: error
    void_checks: error
    always_require_non_null_named_parameters: error
    annotate_overrides: error
    avoid_function_literals_in_foreach_calls: error
    avoid_init_to_null: error
    avoid_null_checks_in_equality_operators: error
    avoid_renaming_method_parameters: error
    avoid_return_types_on_setters: error
    avoid_returning_null_for_void: error
    avoid_single_cascade_in_expression_statements: error
    constant_identifier_names: error
    control_flow_in_finally: error
    empty_constructor_bodies: error
    empty_statements: error
    exhaustive_cases: error
    implementation_imports: error
    library_names: error
    library_prefixes: error
    library_private_types_in_public_api: error
    no_leading_underscores_for_library_prefixes: error
    no_leading_underscores_for_local_identifiers: error
    null_closures: error
    overridden_fields: error
    package_names: error
    prefer_adjacent_string_concatenation: error
    prefer_collection_literals: error
    prefer_conditional_assignment: error
    prefer_contains: error
    prefer_equal_for_default_values: error
    prefer_final_fields: error
    prefer_for_elements_to_map_fromIterable: error
    prefer_function_declarations_over_variables: error
    prefer_if_null_operators: error
    prefer_initializing_formals: error
    prefer_inlined_adds: error
    prefer_interpolation_to_compose_strings: error
    prefer_is_not_operator: error
    prefer_null_aware_operators: error
    prefer_spread_collections: error
    prefer_void_to_null: error
    recursive_getters: error
    slash_for_doc_comments: error
    type_init_formals: error
    unnecessary_brace_in_string_interps: error
    unnecessary_const: error
    unnecessary_constructor_name: error
    unnecessary_getters_setters: error
    unnecessary_late: error
    unnecessary_new: error
    unnecessary_null_aware_assignments: error
    unnecessary_null_in_if_null_operators: error
    unnecessary_nullable_for_final_variable_declarations: error
    unnecessary_string_escapes: error
    unnecessary_string_interpolations: error
    unnecessary_this: error
    use_function_type_syntax_for_parameters: error
    use_rethrow_when_possible: error