name: xayn_discovery_app
description: Xayn discovery app
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.8.1'

# Please list dependencies alphabetically!
dependencies:
  flutter:
    sdk: flutter

  amplitude_flutter: 3.8.0
  appsflyer_sdk: 6.4.4+2
  connectivity_plus: 2.0.3
  equatable: 2.0.3
  envify: 2.0.2
  get_it: 7.0.0
  flutter_bloc: 7.3.1
  flutter_cache_manager: 3.1.3
  flutter_localized_countries:
    git:
      url: https://github.com/xaynetwork/flutter-localized-countries
      ref: 1.0.0
  freezed_annotation: 0.15.0
  fwfh_chewie: 0.7.0+1
  hive: 2.0.4
  hive_crdt: 2.0.2
  # Pointing to a branch where the issue with "deprecated version of the Android embedding" is fixed.
  # Should be updated the to next version when this PR is merged: https://github.com/RainwayApp/flutter_home_indicator/pull/10
  home_indicator:
    git:
      url: https://github.com/nohli/flutter_home_indicator.git
      ref: migrate-to-android-v2-embedding
  http: 0.13.4
  html_unescape: 2.0.0
  hydrated_bloc: 7.1.0
  in_app_purchase: 2.0.1
  in_app_review: 2.0.3
  i18n: 4.0.0-alpha.0
  injectable: 1.5.0
  instabug_flutter: 10.9.1
  intl: 0.17.0
  json_annotation: 4.3.0
  json_serializable: 6.0.0
  logger: 1.1.0
  package_info_plus: 1.3.0
  path_provider: 2.0.5
  provider: 6.0.1
  rxdart: 0.27.3
  share_plus: 3.0.4
  shimmer: 2.0.0
  story:
    git:
      url: git@github.com:xaynetwork/story.git
      ref: cd93531ce08e4afd4490d8bc5f436432a8c0bacd
  url_launcher: 6.0.18
  uuid: 3.0.5
  version: 2.0.0
  xayn_architecture:
    git:
      url: git@github.com:xaynetwork/xayn_architecture.git
      ref: aaffef5c6fd20deddf9978cbd159c4363fb28846
  xayn_card_view:
    git:
      url: git@github.com:xaynetwork/xayn_card_view.git
      ref: 75da7e1cf3df0195b5d7e6c3cd8c991e94d8918d
  xayn_design:
    path: ../../xayn_design
    # git:
    #   url: git@github.com:xaynetwork/xayn_design.git
    #   ref: 62973617479b459af4f35ae08e3572449a9f61a3
  xayn_discovery_engine_flutter:
    git:
      url: git@github.com:xaynetwork/xayn_discovery_engine_release.git
      ### This hash must be the same like the hash in the xayn_discovery_engine dependency override
      ref: fcf40b7b7a6cfbcbbf2caf3f37484d27acaae6fd
      path: discovery_engine_flutter
  xayn_readability:
    git:
      url: git@github.com:xaynetwork/xayn_readability.git
      ref: dd41fca0f847f3a0ff220220b01195ce083a835e
  xayn_swipe_it: 1.0.3

dependency_overrides:
  ### This is necessary because the xayn_discovery_engine_flutter project references the main branch of xayn_discovery_engine
  xayn_discovery_engine:
    git:
      url: git@github.com:xaynetwork/xayn_discovery_engine_release.git
      ### This hash must be the same like the hash in the xayn_discovery_engine_flutter dependency
      ref: fcf40b7b7a6cfbcbbf2caf3f37484d27acaae6fd
      path: discovery_engine

# Please list dependencies alphabetically!
dev_dependencies:
  bloc_test: 8.3.0
  build_runner: 2.1.5
  envify_generator: 2.0.2
  flutter_lints: 1.0.4
  flutter_test:
    sdk: flutter
  freezed: 0.15.0+1
  injectable_generator: 1.5.2
  mockito: 5.0.16

flutter:
  fonts:
    - family: NotoSans
      fonts:
        - asset: packages/xayn_design/assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: packages/xayn_design/assets/fonts/NotoSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: packages/xayn_design/assets/fonts/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf
          weight: 400

  uses-material-design: true

  assets:
    # Including all the files in a directory is not supported for external packages
    # The following could be refactored when this issue is resolved
    # https://github.com/flutter/flutter/issues/27802

    # illustrations
    - packages/xayn_design/assets/illustrations/flag_austria.svg
    - packages/xayn_design/assets/illustrations/flag_belgium.svg
    - packages/xayn_design/assets/illustrations/flag_canada.svg
    - packages/xayn_design/assets/illustrations/flag_germany.svg
    - packages/xayn_design/assets/illustrations/flag_ireland.svg
    - packages/xayn_design/assets/illustrations/flag_netherlands.svg
    - packages/xayn_design/assets/illustrations/flag_poland.svg
    - packages/xayn_design/assets/illustrations/flag_switzerland.svg
    - packages/xayn_design/assets/illustrations/flag_uk.svg
    - packages/xayn_design/assets/illustrations/flag_usa.svg

    # graphics
    - packages/xayn_design/assets/graphics/forms_green.svg
    - packages/xayn_design/assets/graphics/forms_orange.svg
    - packages/xayn_design/assets/graphics/forms_purple.svg
    - packages/xayn_design/assets/graphics/forms_empty_collection.svg

    # icons
    - packages/xayn_design/assets/icons/arrow_down.svg
    - packages/xayn_design/assets/icons/arrow_right.svg
    - packages/xayn_design/assets/icons/diamond.svg
    - packages/xayn_design/assets/icons/search.svg
    - packages/xayn_design/assets/icons/share_android.svg
    - packages/xayn_design/assets/icons/share_ios.svg
    - packages/xayn_design/assets/icons/shield.svg
    - packages/xayn_design/assets/icons/thumbs_down.svg
    - packages/xayn_design/assets/icons/thumbs_down_active.svg
    - packages/xayn_design/assets/icons/thumbs_up.svg
    - packages/xayn_design/assets/icons/thumbs_up_active.svg
    - packages/xayn_design/assets/icons/moon_and_sun.svg
    - packages/xayn_design/assets/icons/move.svg
    - packages/xayn_design/assets/icons/moon.svg
    - packages/xayn_design/assets/icons/sun.svg
    - packages/xayn_design/assets/icons/bookmark.svg
    - packages/xayn_design/assets/icons/bookmark_active.svg
    - packages/xayn_design/assets/icons/plus.svg
    - packages/xayn_design/assets/icons/check.svg
    - packages/xayn_design/assets/icons/premium_decoration.svg
