name: xayn_discovery_app
description: Xayn discovery app
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.5.0'

# Please list dependencies alphabetically!
dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^2.0.3
  envify: ^2.0.0
  get_it: ^7.0.0
  flutter_bloc: ^7.3.1
  flutter_cache_manager: ^3.1.3
  freezed_annotation: ^0.15.0
  hydrated_bloc: ^7.1.0
  http: ^0.13.4
  html_unescape: 2.0.0
  injectable: ^1.2.2
  intl: ^0.17.0
  json_annotation: ^4.3.0
  json_serializable: ^6.0.0
  logger: ^1.0.0
  palette_generator: ^0.3.2
  path_provider: ^2.0.5
  rxdart: ^0.27.2
  share: ^2.0.4
  story:
    git:
      url: git@github.com:xaynetwork/story.git
      ref: 8d747504b5f71f5b9269b6430be65ead43890700
  uuid: ^3.0.5
  xayn_architecture:
    git:
      url: git@github.com:xaynetwork/xayn_architecture.git
      ref: 9d8b3cd842d617ec59b4398ab6e53b29ff8b82a2
  xayn_card_view:
    git:
      url: git@github.com:xaynetwork/xayn_card_view.git
      ref: e98a0d033cbbe3ac4af37c350f19f4d696ffc545
  xayn_design:
    git:
      url: git@github.com:xaynetwork/xayn_design.git
      ref: 645d816c9ce925383c80ee98e5bd8a0f7e789ea8
  xayn_discovery_engine:
    git:
      url: git@github.com:xaynetwork/xayn_discovery_engine.git
      path: discovery_engine
      ref: ef71f30e42f5c6aa5788292adb370ffb5839abbf
  xayn_readability:
    git:
      url: git@github.com:xaynetwork/xayn_readability.git
      ref: cdd428e2eb4586fc267f12e511bb93279f8b8a00
  xayn_swipe_it:
    git:
      url: git@github.com:xaynetwork/xayn_swipe_it.git
      ref: 671a8a74a8df20066f05048c4f156780fe8b4f52

# Please list dependencies alphabetically!
dev_dependencies:
  bloc_test: ^8.3.0
  build_runner: ^2.1.5
  envify_generator: ^2.0.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^0.15.0+1
  injectable_generator: ^1.5.2
  mockito: ^5.0.16

flutter:
  fonts:
    - family: NotoSans
      fonts:
        - asset: packages/xayn_design/assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: packages/xayn_design/assets/fonts/NotoSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: packages/xayn_design/assets/fonts/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf
          weight: 400

  uses-material-design: true

  assets:
    # Including all the files in a directory is not supported for external packages
    # The following could be refactored when this issue is resolved
    # https://github.com/flutter/flutter/issues/27802

    # icons
    - packages/xayn_design/assets/icons/search.svg
    - packages/xayn_design/assets/icons/share_android.svg
    - packages/xayn_design/assets/icons/share_ios.svg
    - packages/xayn_design/assets/icons/shield.svg
    - packages/xayn_design/assets/icons/thumbs_down.svg
    - packages/xayn_design/assets/icons/thumbs_down_active.svg
    - packages/xayn_design/assets/icons/thumbs_up.svg
    - packages/xayn_design/assets/icons/thumbs_up_active.svg