name: xayn_discovery_app
description: Xayn discovery app
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.5.0'

# Please list dependencies alphabetically!
dependencies:
  flutter:
    sdk: flutter

  envify: ^2.0.0
  get_it: ^7.0.0
  flutter_bloc: ^7.3.1
  freezed_annotation: ^0.15.0
  hydrated_bloc: ^7.1.0
  http: ^0.13.4
  injectable: ^1.2.2
  json_annotation: ^4.3.0
  json_serializable: ^6.0.0
  logger: ^1.0.0
  palette_generator: ^0.3.2
  path_provider: ^2.0.5
  rxdart: ^0.27.2
  uuid: ^3.0.5
  xayn_architecture:
    git:
      url: git@github.com:xaynetwork/xayn_architecture.git
      ref: 0bb6b72a7671292735f831d6a1e426176d188d5f
  xayn_design:
    git:
      url: git@github.com:xaynetwork/xayn_design.git
      ref: aabc86fd036a1977eae251081ce3c70d0d12ab8f
  xayn_discovery_engine:
    git:
      url: git@github.com:xaynetwork/xayn_discovery_engine.git
      path: discovery_engine
      ref: ef71f30e42f5c6aa5788292adb370ffb5839abbf
  xayn_readability:
    git:
      url: git@github.com:xaynetwork/xayn_readability.git
      ref: 9b8e4dcd6fd9835097a3d51a8bd19ae77f7bfd60
  xayn_swipe_it:
    git:
      url: git@github.com:xaynetwork/xayn_swipe_it.git
      ref: 04bc3acd355b906cd23ddcf1879ea8543222157d

# Please list dependencies alphabetically!
dev_dependencies:
  bloc_test: ^8.3.0
  build_runner: ^2.1.5
  envify_generator: ^2.0.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^0.15.0+1
  injectable_generator: ^1.5.2
  mockito: ^5.0.16

flutter:
  fonts:
    - family: NotoSans
      fonts:
        - asset: packages/xayn_design/assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: packages/xayn_design/assets/fonts/NotoSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: packages/xayn_design/assets/fonts/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf
          weight: 400

  uses-material-design: true
