name: xayn_discovery_app
description: Xayn discovery app
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.5.0'

# Please list dependencies alphabetically!
dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^2.0.3
  envify: ^2.0.0
  get_it: ^7.0.0
  flutter_bloc: ^7.3.1
  flutter_cache_manager: ^3.1.3
  freezed_annotation: ^0.15.0
  fwfh_chewie: ^0.7.0+1
  hydrated_bloc: ^7.1.0
  http: ^0.13.4
  html_unescape: 2.0.0
  injectable: ^1.2.2
  instabug_flutter: ^10.9.1
  intl: ^0.17.0
  json_annotation: ^4.3.0
  json_serializable: ^6.0.0
  logger: 1.1.0
  package_info_plus: 1.3.0
  path_provider: ^2.0.5
  rxdart: ^0.27.2
  share: ^2.0.4
  shimmer: ^2.0.0
  story:
    git:
      url: git@github.com:xaynetwork/story.git
      ref: cd93531ce08e4afd4490d8bc5f436432a8c0bacd
  uuid: ^3.0.5
  xayn_architecture:
    git:
      url: git@github.com:xaynetwork/xayn_architecture.git
      ref: 0c56db8d7a2c1b27d77354f2698aa3f26bd3cbc6
  xayn_card_view:
    git:
      url: git@github.com:xaynetwork/xayn_card_view.git
      ref: ae0a714239d4e6d3a9d13071e380c2bd0498fde4
  xayn_design:
    git:
      url: git@github.com:xaynetwork/xayn_design.git
      ref: 47f60dfc6f80e258477e5b1eb4b78a0972e95416
  xayn_discovery_engine:
    git:
      url: git@github.com:xaynetwork/xayn_discovery_engine.git
      path: discovery_engine
      ref: ef71f30e42f5c6aa5788292adb370ffb5839abbf
  xayn_readability:
    git:
      url: git@github.com:xaynetwork/xayn_readability.git
      ref: b1c53eb8013d654dc92798f534471da3c4a01dd8
  xayn_swipe_it:
    git:
      url: git@github.com:xaynetwork/xayn_swipe_it.git
      ref: 671a8a74a8df20066f05048c4f156780fe8b4f52

# Please list dependencies alphabetically!
dev_dependencies:
  bloc_test: ^8.3.0
  build_runner: ^2.1.5
  envify_generator: ^2.0.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^0.15.0+1
  injectable_generator: ^1.5.2
  mockito: ^5.0.16

flutter:
  fonts:
    - family: NotoSans
      fonts:
        - asset: packages/xayn_design/assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: packages/xayn_design/assets/fonts/NotoSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: packages/xayn_design/assets/fonts/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf
          weight: 400

  uses-material-design: true

  assets:
    # Including all the files in a directory is not supported for external packages
    # The following could be refactored when this issue is resolved
    # https://github.com/flutter/flutter/issues/27802

    # icons
    - packages/xayn_design/assets/icons/arrow_down.svg
    - packages/xayn_design/assets/icons/arrow_right.svg
    - packages/xayn_design/assets/icons/search.svg
    - packages/xayn_design/assets/icons/share_android.svg
    - packages/xayn_design/assets/icons/share_ios.svg
    - packages/xayn_design/assets/icons/shield.svg
    - packages/xayn_design/assets/icons/thumbs_down.svg
    - packages/xayn_design/assets/icons/thumbs_down_active.svg
    - packages/xayn_design/assets/icons/thumbs_up.svg
    - packages/xayn_design/assets/icons/thumbs_up_active.svg
    - packages/xayn_design/assets/icons/moon_and_sun.svg
    - packages/xayn_design/assets/icons/moon.svg
    - packages/xayn_design/assets/icons/sun.svg
