name: xayn_discovery_app
description: Xayn discovery app
publish_to: 'none'
# this version is only useful for internal tests
version: 3.45.0

environment:
  sdk: '>=2.17.3 <3.0.0'
  flutter: '>=3.0.0'

# Please list dependencies alphabetically!
dependencies:
  flutter:
    sdk: flutter

  airship_flutter: 6.1.0
  app_settings: 4.1.8
  appsflyer_sdk: 6.5.2
  auto_size_text: 3.0.0
  connectivity_plus: 2.2.1
  country_code: 1.0.0
  collection: ^1.16.0
  dart_remote_config:
    git:
      url: https://github.com/xaynetwork/dart_remote_config
      ref: 7ff913391d7f33f0b0c324cd23f05cee19311fbb
  equatable: 2.0.3
  envify: 2.0.2
  flat: ^0.4.1
  flutter_bloc: 7.3.3
  flutter_cache_manager: 3.3.0
  flutter_isolate: 2.0.2
  flutter_local_notifications: 12.0.2
  flutter_localized_countries:
    git:
      url: https://github.com/xaynetwork/flutter-localized-countries
      ref: 1.0.0
  flutter_tts: 3.5.0
  # language detection
  franc:
    git:
      url: https://github.com/svonidze/francd
      ref: 170e633af9a7b8b31769eb232f99e105e1359692
  freezed_annotation: 2.1.0
  fwfh_chewie: 0.7.0+1
  get_it: 7.2.0
  gibberish:
    git:
      url: https://github.com/xaynetwork/gibberish
      ref: 0.1.0
  hive: 2.0.5
  hive_crdt: 2.0.2
  # Pointing to a branch where the issue with "deprecated version of the Android embedding" is fixed.
  # Should be updated the to next version when this PR is merged: https://github.com/RainwayApp/flutter_home_indicator/pull/10
  home_indicator:
    git:
      url: https://github.com/nohli/flutter_home_indicator.git
      ref: migrate-to-android-v2-embedding
  http: 0.13.4
  html: 0.15.0
  html_unescape: 2.0.0
  hydrated_bloc: 7.1.0
  in_app_notification: 1.1.1
  in_app_review: 2.0.4
  i18n: 4.0.0-alpha.0
  injectable: 1.5.3
  instabug_flutter: 10.13.0
  intl: 0.17.0
  json_annotation: 4.3.0
  json_serializable: 6.1.4
  logger: 1.1.0
  lottie: 1.2.2
  mixpanel_flutter: 1.5.0
  notification_permissions:
    git:
      url: https://github.com/bshvets8/flutter_notification_permissions.git
      ref: feature/android-13-support
  package_info_plus: 1.4.0
  path_provider: 2.0.9
  purchases_flutter: 4.0.0-beta.1
  platform: ^3.1.0
  rxdart: 0.27.3
  sprintf: 6.0.0
  share_plus: 4.0.3
  shimmer: 2.0.0
  super_rich_text:
    git:
      url: https://github.com/Bestfastfire/super_rich_text.git
      ref: f9d3963421682e2e0dd99c1ab553b99e38766ea1
  system_info2: 2.0.3
  quiver: 3.0.1+1
  url_launcher: 6.0.20
  uuid: 3.0.6
  version: 2.0.0
  xayn_architecture:
    git:
      url: https://github.com/xaynetwork/xayn_architecture.git
      ref: 8f9a75deaea65b19f847393d83ec56bd81803d19
  xayn_card_view:
    git:
      url: https://github.com/xaynetwork/xayn_card_view.git
      ref: 1665c64af48058f116ffa0e71296c7748c3c6c1e
  xayn_design:
    git:
      url: https://github.com/xaynetwork/xayn_design.git
      ref: e19b3ad8ef07e2349b250abac8c27cddec68beef
  xayn_discovery_engine_flutter:
    hosted: https://xayn.jfrog.io/artifactory/api/pub/dart.xayn.private
    version: 0.1.0+main.220914085310
  xayn_readability:
    git:
      url: https://github.com/xaynetwork/xayn_readability.git
      ref: e37cd9d4b33ddfb30469f260e11b6692beac1c88
  xayn_swipe_it: 1.0.4

dependency_overrides:
  json_annotation: 4.4.0
  hive: 2.1.0
  analyzer: 4.2.0
  provider: 6.0.2
  dart_style: 2.2.2
  json_serializable: 6.1.4
  build_resolvers: 2.0.9
  source_gen: 1.2.2
  source_helper: 1.3.2

# Please list dependencies alphabetically!
dev_dependencies:
  bloc_test: 8.5.0
  build_runner: 2.2.1
  envify_generator: 2.0.2
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  freezed: 2.1.0+1
  injectable_generator: 1.5.3
  mockito: 5.1.0

flutter:
  fonts:
    - family: NotoSans
      fonts:
        - asset: packages/xayn_design/assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: packages/xayn_design/assets/fonts/NotoSans-Bold.ttf
          weight: 700
    - family: NotoSerif
      fonts:
        - asset: packages/xayn_design/assets/fonts/NotoSerif-Regular.ttf
          weight: 400
        - asset: packages/xayn_design/assets/fonts/NotoSerif-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: packages/xayn_design/assets/fonts/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf
          weight: 400

  uses-material-design: true

  assets:
    # This must be the real toplevel directories for the AI assets.
    # Whenever the manifest changes this must be updated to contain the correct folders.
    # In order to determine the real folder structure run:
    # fastlane clean && fastlane build_runner  (which will run the update_assets lane and download the assets)
    - assets/ai/kpe_v0001/
    - assets/ai/smbert_v0001/
    - assets/ai/sources_v0000/
    - assets/remote_config/

    # Including all the files in a directory is not supported for external packages
    # The following could be refactored when this issue is resolved
    # https://github.com/flutter/flutter/issues/27802

    # illustrations
    - packages/xayn_design/assets/illustrations/flag_austria.svg
    - packages/xayn_design/assets/illustrations/flag_argentina.svg
    - packages/xayn_design/assets/illustrations/flag_belgium.svg
    - packages/xayn_design/assets/illustrations/flag_canada.svg
    - packages/xayn_design/assets/illustrations/flag_colombia.svg
    - packages/xayn_design/assets/illustrations/flag_france.svg
    - packages/xayn_design/assets/illustrations/flag_germany.svg
    - packages/xayn_design/assets/illustrations/flag_ireland.svg
    - packages/xayn_design/assets/illustrations/flag_italy.svg
    - packages/xayn_design/assets/illustrations/flag_mexico.svg
    - packages/xayn_design/assets/illustrations/flag_netherlands.svg
    - packages/xayn_design/assets/illustrations/flag_peru.svg
    - packages/xayn_design/assets/illustrations/flag_poland.svg
    - packages/xayn_design/assets/illustrations/flag_russia.svg
    - packages/xayn_design/assets/illustrations/flag_switzerland.svg
    - packages/xayn_design/assets/illustrations/flag_uk.svg
    - packages/xayn_design/assets/illustrations/flag_usa.svg
    - packages/xayn_design/assets/illustrations/flag_turkey.svg
    - packages/xayn_design/assets/illustrations/flag_ukraine.svg
    - packages/xayn_design/assets/illustrations/enable_camera.svg

    # lottie
    - packages/xayn_design/assets/lottie/bookmark_click.json
    - packages/xayn_design/assets/lottie/feed_swipe_vertical.json
    - packages/xayn_design/assets/lottie/feed_swipe_horizontal.json
    - packages/xayn_design/assets/lottie/mange_collection.json
    - packages/xayn_design/assets/lottie/splash_screen.json
    - packages/xayn_design/assets/lottie/splash_screen_dark.json
    - packages/xayn_design/assets/lottie/survey.json
    - packages/xayn_design/assets/lottie/source_selection.json
    - packages/xayn_design/assets/lottie/country_selection.json

    # lottie contextual illustrations
    - packages/xayn_design/assets/lottie/contextual/create_collection.json
    - packages/xayn_design/assets/lottie/contextual/delete_collection.json
    - packages/xayn_design/assets/lottie/contextual/empty_collection.json
    - packages/xayn_design/assets/lottie/contextual/empty_search.json
    - packages/xayn_design/assets/lottie/contextual/empty_sources.json
    - packages/xayn_design/assets/lottie/contextual/empty_sources_lookup.json
    - packages/xayn_design/assets/lottie/contextual/empty_sources_mgmt.json
    - packages/xayn_design/assets/lottie/contextual/error.json
    - packages/xayn_design/assets/lottie/contextual/no_image_1.json
    - packages/xayn_design/assets/lottie/contextual/no_image_2.json
    - packages/xayn_design/assets/lottie/contextual/no_image_3.json
    - packages/xayn_design/assets/lottie/contextual/no_image_4.json
    - packages/xayn_design/assets/lottie/contextual/payment_failed.json
    - packages/xayn_design/assets/lottie/contextual/payment_pending.json
    - packages/xayn_design/assets/lottie/contextual/premium.json
    - packages/xayn_design/assets/lottie/contextual/source_filter.json
    - packages/xayn_design/assets/lottie/contextual/subscription_active.json

    # graphics
    - packages/xayn_design/assets/graphics/forms_green.svg
    - packages/xayn_design/assets/graphics/forms_orange.svg
    - packages/xayn_design/assets/graphics/forms_purple.svg
    - packages/xayn_design/assets/graphics/forms_empty_collection.svg

    # icons
    - packages/xayn_design/assets/icons/arrow_down.svg
    - packages/xayn_design/assets/icons/arrow_right.svg
    - packages/xayn_design/assets/icons/bookmark.svg
    - packages/xayn_design/assets/icons/bookmark_active.svg
    - packages/xayn_design/assets/icons/check.svg
    - packages/xayn_design/assets/icons/diamond.svg
    - packages/xayn_design/assets/icons/font_size.svg
    - packages/xayn_design/assets/icons/globe.svg
    - packages/xayn_design/assets/icons/home.svg
    - packages/xayn_design/assets/icons/home_active.svg
    - packages/xayn_design/assets/icons/moon.svg
    - packages/xayn_design/assets/icons/moon_and_sun.svg
    - packages/xayn_design/assets/icons/move.svg
    - packages/xayn_design/assets/icons/person.svg
    - packages/xayn_design/assets/icons/person_active.svg
    - packages/xayn_design/assets/icons/plus.svg
    - packages/xayn_design/assets/icons/premium_decoration.svg
    - packages/xayn_design/assets/icons/search.svg
    - packages/xayn_design/assets/icons/search_active.svg
    - packages/xayn_design/assets/icons/share_android.svg
    - packages/xayn_design/assets/icons/share_ios.svg
    - packages/xayn_design/assets/icons/shield.svg
    - packages/xayn_design/assets/icons/sun.svg
    - packages/xayn_design/assets/icons/text.svg
    - packages/xayn_design/assets/icons/text_large_font.svg
    - packages/xayn_design/assets/icons/text_medium_font.svg
    - packages/xayn_design/assets/icons/text_sans.svg
    - packages/xayn_design/assets/icons/text_serif.svg
    - packages/xayn_design/assets/icons/text_small_font.svg
    - packages/xayn_design/assets/icons/thumbs_down.svg
    - packages/xayn_design/assets/icons/thumbs_down_active.svg
    - packages/xayn_design/assets/icons/thumbs_up.svg
    - packages/xayn_design/assets/icons/thumbs_up_active.svg
