name: source_query
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.16.1 <3.0.0'

# Please list dependencies alphabetically!
dependencies:
  http: ^0.13.4
  html: ^0.15.0
#  fast_gbk: ^1.0.0
  enough_convert: ^1.4.0

# Please list dependencies alphabetically!
dev_dependencies:
