# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)


desc "Build internal apk"
private_lane :android_prepare_internal do |options|
  UI.user_error!("No PROVISIONING_PASSWORD provided!") unless ENV.key?("PROVISIONING_PASSWORD")
  writeKeyProperties(ENV["PROVISIONING_PASSWORD"])
end

def writeKeyProperties(provisionigPassword) 
  File.open('../key.properties', 'w') do |fo|
    fo.write("storePassword=#{provisionigPassword}\n")
    fo.write("keyPassword=#{provisionigPassword}\n")
    fo.write("keyAlias=release\n")
    fo.write("storeFile=internal_release.jks\n")
  end
end