# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

desc "Create a signed IPA package"
private_lane :ios_create_ipa do |options|
  UI.user_error!("No PROVISIONING_PASSWORD provided!") unless ENV.key?("PROVISIONING_PASSWORD")
  shouldDownloadProfile = options[:downloadProfile]
  if shouldDownloadProfile
    UI.user_error!("No APPSTORE_API_KEY provided (you can run create_appstore_api_key)!") unless ENV.key?("APPSTORE_API_KEY")
  end

  begin
    delete_keychain(name: "fastlane_tmp_keychain-db")
  rescue Exception
  end
  create_keychain(
    name: "fastlane_tmp_keychain-db",
    default_keychain: true,
    unlock: true,
    timeout: 0,
    lock_when_sleeps: false,
    password: "",
  )
  if is_ci
    setup_ci(force: true)
  end

  import_certificate(
    certificate_path: "profiles/Certificates-internal.p12",
    certificate_password: ENV["PROVISIONING_PASSWORD"],
    keychain_name: "fastlane_tmp_keychain-db",
    keychain_password: "",
  )

  # This ensures that provisioning profiles are uptodate with the latest registered devices
  if shouldDownloadProfile
    get_provisioning_profile(
        adhoc: true,
        force: false,
        filename: "profiles/Xayn_Discovery_Internal_Adhoc_Profile.mobileprovision",
        provisioning_name:  "Xayn Discovery Internal Adhoc Profile",
        api_key: JSON.parse(ENV["APPSTORE_API_KEY"]),
        ignore_profiles_with_different_name: true,
        skip_certificate_verification: true,
      )
  end
  install_provisioning_profile(
    path: "profiles/Xayn_Discovery_Internal_Adhoc_Profile.mobileprovision",
  )

  build_app(scheme: "Runner",
            configuration: "Release",
            workspace: "Runner.xcworkspace",
            export_method: "ad-hoc",
            export_options: {
              "uploadBitcode" => false,
              provisioningProfiles: {
                "com.xayn.discovery.internal" => "Xayn Discovery Internal Adhoc Profile",
              },
            },
            include_bitcode: false,
            skip_profile_detection: true,
            output_directory: "../build/",
            output_name: "discovery-app.ipa")
  delete_keychain(name: "fastlane_tmp_keychain-db")
end

desc "Create an app store connect api key "
lane :create_appstore_api_key do |options|
  UI.user_error!("keyFile missing - No p8 key file provided. Create and download keys here:  https://appstoreconnect.apple.com/access/api !") unless options[:keyFile]
  UI.user_error!("keyId missing") unless options[:keyId]
  UI.user_error!("issuerId missing") unless options[:issuerId]

  keyfile = options[:keyFile]
  keyId = options[:keyId]
  issuerId = options[:issuerId]
  keyContent = sh("base64 ../#{keyfile}")

  key = app_store_connect_api_key(
    key_id: keyId,
    issuer_id: issuerId,
    key_content: keyContent,
    is_key_content_base64: true,
    in_house: true,
    duration: 1200,
  )
  UI.message "Json Key:\n\n#{key.to_json}"
end
