name: Basic checks

env:
  FLUTTER_VERSION: "2.5.3"

on:
  pull_request:
    branches:
      - '*'

jobs:
  Basic-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: britannio/action-install-flutter@v1
        with:
          version: $FLUTTER_VERSION

      - name: Run checks
        env:
          SEARCH_API_SECRET_DEBUG: ${{ secrets.SEARCH_API_SECRET_DEBUG }}
          SEARCH_API_SECRET_PRODUCTION: ${{ secrets.SEARCH_API_SECRET_PRODUCTION }}
          FASTLANE_SKIP_UPDATE_CHECK: "1"
        working-directory: ./application
        run: |
          sudo chmod -R a+w /var/lib/gems/
          fastlane check
