name: Code Quality

env:
  FLUTTER_VERSION: '2.10.0'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  Basic-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: gitleaks-action
        uses: zricethezav/gitleaks-action@master
        with:
          config-path: .gitleaks.toml

      - name: Install Flutter
        uses: britannio/action-install-flutter@v1
        with:
          version: $FLUTTER_VERSION

      - name: Install lcov and jq
        run: |
          sudo apt install lcov jq

      - name: Run checks
        timeout-minutes: 20
        env:
          SEARCH_API_SECRET_DEBUG: ${{ secrets.SEARCH_API_SECRET_DEBUG }}
          SEARCH_API_SECRET_PRODUCTION: ${{ secrets.SEARCH_API_SECRET_PRODUCTION }}
          INSTABUG_TOKEN_DEBUG: ${{ secrets.INSTABUG_TOKEN_DEBUG }}
          INSTABUG_TOKEN_PRODUCTION: ${{ secrets.INSTABUG_TOKEN_PRODUCTION }}
          AMPLITUDE_API_KEY_DEBUG: ${{ secrets.AMPLITUDE_API_KEY_DEBUG }}
          AMPLITUDE_API_KEY_PRODUCTION: ${{ secrets.AMPLITUDE_API_KEY_PRODUCTION }}
          APPSFLYER_DEV_KEY: ${{ secrets.APPSFLYER_DEV_KEY }}
          REVENUE_CAT_SDK_KEY_ANDROID: ${{ secrets.REVENUE_CAT_SDK_KEY_ANDROID }}
          REVENUE_CAT_SDK_KEY_IOS: ${{ secrets.REVENUE_CAT_SDK_KEY_IOS }}
          FASTLANE_SKIP_UPDATE_CHECK: '1'
        working-directory: ./application
        run: |
          sudo chmod -R a+w /var/lib/gems/
          fastlane check