name: Basic checks

env:
  FLUTTER_VERSION: "2.5.3"

on:
  pull_request:
    branches:
      - '*'

jobs:
  Basic-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: britannio/action-install-flutter@v1
        with:
          version: $FLUTTER_VERSION

      - name: Get Packages
        run: |
          cd application
          flutter pub get
          cd -
      - name: Run build_runner
        run: |
          cd application
          flutter pub run build_runner build --delete-conflicting-outputs
          cd -
      - name: Flutter format
        run: |
          cd application
          flutter format ./ --set-exit-if-changed
          cd -
      - name: Flutter Analyze
        run: |
          cd application
          flutter analyze lib test
          cd -
      - name: Run Tests
        run: |
          cd application
          flutter test
          cd -
