name: Testing

on:
  pull_request:

permissions:
  contents: read

jobs:
  s3-test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::165060789769:role/xayn-data-storage-role
          aws-region: eu-central-1

      - name: Download 
        run: |
          aws s3api get-object --bucket xayn-data-storage --key test.txt 
